### ISSUE TITLE
Regierungsbezirke is outdated

### ISSUE THREAD

**Issue by klaemo** [isellsoap/deutschlandGeoJSON#10]
It looks like the Regierungsbezirke (NUTS2) file is somewhat outdated. `Dessau`, `Halle` and `Magdeburg` are now grouped as `Sachsen-Anhalt`.

See https://de.wikipedia.org/wiki/NUTS:DE#%C3%9Cbersicht_%C3%BCber_die_NUTS-2-Regionen_in_Deutschland

I'm currently trying to find suitable GeoJSON for this and will report back!

**Comment by mighty190E** [comment]
To me it seems like all the Information from "Kreisreform" 2008 is missing.
There are a bunch of "Landkreise" that no longer exist and were grouped together.

So for me this dataset does not work out because I am reliant on the correct "Landkreise"

More information:
https://de.wikipedia.org/wiki/Kreisreform_Sachsen_2008

**Comment by FriedrichSal** [comment]
This is a great dataset! 

Just noting that the Kreise in Mecklenburg-Vorpommern also seem outdated since they due not reflect the Kreisgebietsreform from 2011. 

https://de.wikipedia.org/wiki/Kreisgebietsreform_Mecklenburg-Vorpommern_2011. The data has 18 Kreise, but Meckelnburg-Vorpommern currently only has 8.

**Comment by FriedrichSal** [comment]
I checked the data on [Diva-gis](http://www.diva-gis.org/gdata), which is the data source for this repo - the data there also seems outdated. So not much to be done.

**Comment by jccabrejas** [comment]
Have a look in [Bundesamt für Kartographie und Geodäsie](https://gdz.bkg.bund.de/index.php/default/open-data/ )

As an example, [Verwaltungsgebiete 1:2 500 000, Stand 01.01. (VG2500)](https://gdz.bkg.bund.de/index.php/default/open-data/verwaltungsgebiete-1-2-500-000-stand-01-01-vg2500.html) is from Jan 1st 2020

**Comment by Praesklepios** [comment]
I advice to use my repo instead: [geoGermany](https://github.com/Praesklepios/geoGermany).

It saves you the pain working with outdated data, has the ARS listed and more region-layers available.

**Comment by isellsoap** [comment]
@Praesklepios Thanks for jumping in and linking to your project. 

I will add a notice that this repository is not being actively monitored and worked on. I don’t have the time to manage it anymore.

**Comment by isellsoap** [comment]
Hi @klaemo, thanks for opening the issue. This project will be archived, because I won’t be able to maintain it anymore. Feel free to fork it and make it your own. Thanks a lot.
